
language: R

cache: packages

sudo: false

dist: trusty

warnings_are_errors: false

r_packages:
  - data.table
  - digest
  - rjson

notifications:
  email:
    on_success: change
    on_failure: change

