
matrix:
  include:
    - language: r
      r: release
      cache: packages
      sudo: false
      dist: trusty
      warnings_are_errors: false
      r_packages:
        - data.table
        - digest
        - rjson
    - language: python
      python: 3.5
      install:
        - pip install -r requirements.txt
      script:
        - setup.py test

notifications:
  email:
    on_success: change
    on_failure: change

