
cache: packages
sudo: false

matrix:
  include:
    - language: r
      r: oldrel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=$(which python3)
      # install the python package first
      before_install:
        - pyenv shell 3.6
        - pip3 install numpy pandas
        - ./setup.py install
      dist: trusty

    - language: r
      r: release
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=$(which python3)
      # install the python package first
      before_install:
        - pyenv shell 3.6
        - pip3 install numpy pandas
        - ./setup.py install
      dist: trusty

    - language: r
      r: devel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=$(which python3)
      # install the python package first
      before_install:
        - pyenv shell 3.6
        - pip3 install numpy pandas
        - ./setup.py install
      dist: trusty

    - language: python
      python: 3.4
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.5
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.6
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

  allow_failures:
    - r: devel

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

