
cache: packages
sudo: false

matrix:
  include:
    # - language: r
    #   r: oldrel
    #   # install the python package first
    #   addons:
    #     apt:
    #       packages:
    #       - "python3"
    #       - "python3-pip"
    #   env:
    #     - RETICULATE_PYTHON=$(which python3)
    #   before_install:
    #     - pip3 install numpy pandas
    #     - ./setup.py install
    #   dist: trusty

    - language: r
      r: release
      addons:
        apt:
          packages:
          - "python3"
          - "python3-pip"
      env:
        - RETICULATE_PYTHON=$(which python3)
      # install the python package first
      before_install:
        - pip3 install .
       # -r requirements.txt
        - ./setup.py install
      dist: trusty

    # - language: r
    #   r: devel
    #   env:
    #     - RETICULATE_PYTHON=$(which python3)
    #   # install the python package first
    #   before_install:
    #     - pip3 install numpy pandas
    #     - ./setup.py install
    #   dist: trusty

    # - language: python
    #   python: 3.4
    #   install:
    #     - pip install -r requirements.txt
    #   script:
    #     - python setup.py test

    # - language: python
    #   python: 3.5
    #   install:
    #     - pip install -r requirements.txt
    #   script:
    #     - python setup.py test

    # - language: python
    #   python: 3.6
    #   install:
    #     - pip install -r requirements.txt
    #   script:
    #     - python setup.py test

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

