
cache: packages
sudo: false

matrix:
  include:
    - language: r
      r: oldrel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3.5
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3.5 python3.5-dev python3-pip
        - sudo python3.5 -m pip install numpy pandas
        - python3.5 setup.py install --user
      dist: trusty

    - language: r
      r: release
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3.5
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3.5 python3.5-dev python3-pip
        - sudo python3.5 -m pip install numpy pandas
        - python3.5 setup.py install --user
      dist: trusty

    - language: r
      r: devel
      env:
        - NOMIS_API_KEY=DUMMY
        - RETICULATE_PYTHON=/usr/bin/python3.5
      # install the python package first
      before_install:
        - sudo apt-get update && sudo apt-get install -y python3.5 python3.5-dev python3-pip
        - sudo python3.5 -m pip install numpy pandas
        - python3.5 setup.py install --user
      dist: trusty

    - language: python
      python: 3.7-dev
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.5
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.6
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

  allow_failures:
    - r: oldrel
    - r: release
    - r: devel

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack: spenser-workspace:QzyXfMnQd5tUJaFZPK6Psl4M
