
matrix:
  include:
    - language: r
      r: release
      cache: packages
      sudo: false
      dist: trusty
      r_packages:
        - data.table
        - digest
        - rjson

    - language: r
      r: devel
      cache: packages
      sudo: false
      dist: trusty
      r_packages:
        - data.table
        - digest
        - rjson

    - language: python
      python: 
        - 3.5
        - 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test
      
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

