
cache: packages
sudo: false

matrix:
  include:
    - language: r
      r: oldrel
      cache: packages
      dist: trusty

    - language: r
      r: release
      # install the python package first
#      before_install:
#        - pip install numpy pandas
#        - ./setup.py install
      cache: packages
      dist: trusty

    - language: r
      r: devel
      cache: packages
      dist: trusty

    - language: python
      python: 3.4
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.5
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

    - language: python
      python: 3.6
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

